### ISSUE TITLE
Catalina

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#372]
It's expected some things don't work in Catalina
- [x] Emulate Rez => #384 
- [x] Probably need to implement AUv2 + Audio Component API for this reason => #104 , possibly remove ComponentManager older API. Do like other plugin developers.
- [x] tell users to avoid Catalina (not yet)
- [x] Notarization => #358 
- [x] Fix AAX signing => #381 
- [x] upgrade to latest LDC with catalina fix => #373 to solve before`
- [x] 10.15 Catalina testing
- [x] test logic validation on 10.15
- [x] test auval on 10.15

**Comment by p0nce** [comment]
Everything looks ready now! And before Apple is :)
