### ISSUE TITLE
Big Sur support including ARM64

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#458]
To prepare for future macOS being ARM-based, need to support `-mtriple=arm64-apple-macos`

- [x] `dplug-build` can do Universal Build again => #490
- [x] `intel-intrinsics` ported to ARM64 and optimised
- [x] `pfft` ported to ARM64 (EDIT: could probably be a bit faster) with Travis CI
- [x] `gfm` ported to ARM64, with Travis CI
- [x] `dplug` ported to ARM64, with Travis CI
- [x] `dplug.core.debugBreak`
- [x] save/restore of FPCR in `fpcontrol.d` (EDIT: dplug:core will simply depends on ` intel-intrinsics` for SSE control word)
- [x] druntime support for `arm64-apple-macos` => https://github.com/ldc-developers/ldc/issues/3559
- [x] fix the damn CI
- [x] Can build UB and arm64 VST3
- [x] Can build UB and arm64 AU
- [x] Can build UB and arm64 VST2
- [x] Manage AAX and LV2 by disabling UB and arm64 for those => actually dplug-build will stay x86_64
- [x] try full build on Mac with optimisations
- [x] Surprise: UISwitchOnOff are not lightened on click. Time problem?  => #496 
- [x] Panagement crash after a while in Big Sur => #497
- [x] full build including installer
- [x] full build including notarization (EDIT: nice, previous app-specific passwords work)
- [x] find a host that works in arm64 or at least x86_64 => Live beta and reaper pre-release builds
- [x] test on REAPER arm64 => #494 
- [x] test on latest Logic arm64
- [x] fix #498 in Logic
- [x] fix #499 in Logic
- [x] fix Logic AU validation => #501
- [x] test on Ableton Live beta => OK for x86_64 but arm64 doesn't load, Live isn't ported itself. It sounds like an x86_64 binary will not load arm64 shared libraries? => **Try with process**
- [x] test load of arm64 lib by x86_64 host
- [x] Update to latest Xcode => this one doesn't launch its IDE under Big Sur beta 1, but the SDK work as well as Xcode 12 beta1.
- [x] Why does `process` show `Bad Address`?
- [x] test on Pro Audio seed MainStage => it just doesn't load
- [x] test on latest Big Sur => a PITA to update... (EDIT: abandon for now, I don't have mobile data left thanks to failed downloads...)
- [x] DUB has failure to find every files... random failure often => honestly, sounds like a Big Sur beta bug.
- [x] Find what makes so much warning when building the runtime.
- [x] `latency-check` arm64 can load an arm64 plug-in
- [x] find why `process` doesn't work correctly => #494 probably

Open questions:
- [x] How to support Universal Binary AAX plugins? since dplug-build will only extract presets for build arch it was built with. (same with LV2, but doesn't exist in macOS so less stringent) => dplug-buid will stay x86_64 but able to build arm64.
- [x] How to support .rsrc files ? Not sure there is an enum in Rez for an ARM64 entry point. => it was easy to add a callback

Compatibility table, what is supposed to work in Rosetta 2?
- arm64 host and arm64 shared library => yes
- arm64 host and x86_64 shared library => no? `dlopen` fails with process arm64 + x86_64 plugin
- arm64 host with UB2 shared library => yes
- x86_64 host and arm64 shared library => no? `dlopen` fails with process x86_64 + arm64 plugin
- x86_64 host and x86_64 shared library => yes
- x86_64 host with UB2 shared library => yes

**Comment by 0xEAB** [comment]
*armhf* (aka `arm-linux-gnueabihf`) might also be interesting.
Relevant for (devices): Raspberry Pi

**Comment by abaga129** [comment]
ARM would be very cool to support.  As @0xEAB said Raspberry Pi is one of those devices, and as far as I know, there isn't any support for it by other frameworks.  We could potentially fill that niche.

**Comment by 0xEAB** [comment]
What would be the correct way to with the missing x87 support on *arm-linux-gnueabihf*?

`../../core/dplug/core/math.d(428,5): Error: static assert:  "Unable to implement Real80 on this architecture"`

**Comment by p0nce** [comment]
Real80 isn't used I believe because in actual use on Windows 64-bit with LDC precision was limited to double mantissa even if FPU was involved. You can remove it I believe.

**Comment by p0nce** [comment]
Some performance numbers of Rosetta2 vs native arm64:

```
arm64, LDC 1.24 --final
Results:
 * minimum time: 81.7 ms => 30.34 x real-time
 * median  time: 81.8 ms => 30.29 x real-time
 * average time: 82.0 ms => 30.24 x real-time

x86_64, LDC 1.24 -final
Results:
 * minimum time: 155.1 ms => 15.99 x real-time
 * median  time: 155.3 ms => 15.96 x real-time
 * average time: 155.5 ms => 15.94 x real-time
```
It's not fantastic but not bad either.

**Comment by p0nce** [comment]
I think it's OK to release now, I hope the following 3 problems are just because I use a beta macOS with a beta Logic
- Logic not forwarding keyDown events to super class => #499 
- Logic demanding arm64**e** arch in internal validation => #501 
- huge memory leak of CIImage => #497

**Comment by p0nce** [comment]
Everything sounds approximately ready, apart from intel-intrinsics performance concern, nothing has been really profiled on arm64.
