### ISSUE TITLE
Conditional widgets

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#849]
The issue is that at this point I have:

 - UICondKnob
 - UICondSlider
 - UICondSwitch
etc etc.
So there is about 10 conditional widget in Auburn codebase.

All points towards a smallish Condition interpreter that can parse and evaluate an expression tree at given points in time (typically, when a listened parameter changes). For now the expression tree is implemented in Auburn codebase in a lame fixed way ( a set of && or || expressions, with 2 operators).

Ideally we want:
- the 4 operators: < > >= <=, 
- boolean and double expressions
- && and ||
- access to parameter
The expression itself is evaluated when it's value may have changed.
This evaluation will happen for many widgets, even inside audio thread as part of a host setParameter, and myst be quick!
- there is a pre-parse that registers / deregisters Parameter to be listened to.

This will allows the agreeable idioms:
- `widget.enableIf(string expr);` to control the .isDisabled state
- `widget.showIf(string expr);` to control visibility

Any widget has such a conditional extension. This will avoid the existence of: 

**Stage 1**
- [ ] Add existing owned `CondLogic` as a lazy extension of all `UIElement`. It's a set of || or && expression, suitable for most purposes but not very readable.
- [ ] All UIElement have a queryable `.isEnabled` and `.isDisabled`. By default true, unless the condition is created  and return false.

Now the sub-class are easier to write, but there are still multiple subclasses. This is 80% of the value.

**Stage 2**
- [ ] Add an additional `.enableIf` call to UIElement that created the `CondLogic` and 
- [ ] Implement `widget.enableIf`
- [ ] expression interpreter registers the listeners
- [ ] expression interpreter eval the condition
- [ ] The big issue is that because of our imperative styling, there is no way to not subclass in order to add the diffuseDisabled RGBA variables. Undoing that needs more declarative.
- [ ]  - [ ] Should this be Wren? Should this be fe-d, a Forth-like?
